<?php

/**
 * @file
 * Adds support for sending SMS messages using the huyi gateway.
 */

/**
 * Implements hook_gateway_info().
 */
function sms_huyi_gateway_info() {
  return array(
    'huyi' => array(
      'name' => 'huyi',
      'configure form' => 'sms_huyi_admin_form',
      'receive' => FALSE,  //no need message incoming now.
      'send' => 'sms_huyi_send',
      'send form' => 'sms_huyi_send_form',
    ),
  );
}

/**
 * Admin/settings form.
 */
function sms_huyi_admin_form($configuration) {
  $form['sms_huyi_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Huyi url'),
    '#description' => t('huyi url'), // http://106.ihuyi.cn/webservice/sms.php
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_huyi_url']) ? $configuration['sms_huyi_url'] : '',
  );
  $form['sms_huyi_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Account name'),
    '#description' => t('huyi account name'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_huyi_account']) ? $configuration['sms_huyi_account'] : '',
  );
  $form['sms_huyi_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Huyi Pass'),
    '#description' => t('Pass of huyi'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_huyi_password']) ? $configuration['sms_huyi_password'] : '',
  );
  return $form;
}

/**
 * Validates the submission of the configuration form.
 */
function sms_huyi_admin_form_validate($form, &$form_state) {
}

/**
 * Returns custom additions to be added to the send forms
 */
function sms_huyi_send_form() {
	$form = array();
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_huyi_send($number, $message, $options = NULL) {
  $number = preg_replace("/[^0-9]/", '', $number);
  $number = trim($number);
  $number = ltrim($number, '0'); // Remove leading zeros
  $gateway = sms_gateways('gateway', 'huyi');
  $config = $gateway['configuration'];
  $url = $config['sms_huyi_url'];
  $account = $config['sms_huyi_account'];
  $pass = $config['sms_huyi_password'];
  $post_data = "account=" .$account. "&password=" . $pass . "&mobile=".$number."&content=".rawurlencode("您的验证码是：". $message ."。请不要把验证码泄露给其他人。");
  //密码可以使用明文密码或使用32位MD5加密
  $xml_result = Post($post_data, $url);
  $gets =  xml_to_array($xml_result);
  watchdog('sms_huyi', print_r($gets, TRUE));
  // Check for HTTP errors
  if ($gets['SubmitResult']['code']==2) {
  	$result = array(
  			'status' => TRUE,
  			'data' => t('Message sent to @number', array('@number' => $number)),
  	);
  }
  else {  	
  	$result = array(
  			'status' => FALSE,
  			'message' => t('An error occured during the HTTP request: @error', array('@error' => $gets['SubmitResult']['msg'])),
  	);
  }
  return $result;
}

function Post($curlPost,$url){
	$curl = curl_init();
	curl_setopt($curl, CURLOPT_URL, $url);
	curl_setopt($curl, CURLOPT_HEADER, false);
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($curl, CURLOPT_NOBODY, true);
	curl_setopt($curl, CURLOPT_POST, true);
	curl_setopt($curl, CURLOPT_POSTFIELDS, $curlPost);
	$return_str = curl_exec($curl);
	curl_close($curl);
	return $return_str;
}
function xml_to_array($xml){
	$reg = "/<(\w+)[^>]*>([\\x00-\\xFF]*)<\\/\\1>/";
	if(preg_match_all($reg, $xml, $matches)){
		$count = count($matches[0]);
		for($i = 0; $i < $count; $i++){
			$subxml= $matches[2][$i];
			$key = $matches[1][$i];
			if(preg_match( $reg, $subxml )){
				$arr[$key] = xml_to_array( $subxml );
			}else{
				$arr[$key] = $subxml;
			}
		}
	}
	return $arr;
}