<?php
/**
 * Implements hook_block_info().
 */
function event_filter_block_info() {
	$blocks ['event_filter_top_menu'] = array (
			'info' => t ( 'Top menu filter on touzi event.' ),
			'cache' => DRUPAL_CACHE_PER_ROLE 
	);
	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function event_filter_block_view($delta = '') {
	switch ($delta) {
		case 'event_filter_top_menu' :
			$block ['subject'] = t ( 'Top menu filter on touzi event.' );
			$block ['content'] = event_filter_top_menu_contents ( $delta );
			break;
	}
	return $block;
}
function event_filter_top_menu_contents($delta) {
	$content = '<div class="parent_terms"><ul class="list-unstyled left-nav">';
	$sql = "SELECT td.tid, td.name
            FROM taxonomy_term_data td
            INNER JOIN taxonomy_vocabulary v ON v.vid = td.vid
            inner join taxonomy_term_hierarchy th on td.tid=th.tid and th.parent=0
            WHERE v.vid = 8
            ORDER BY td.weight, td.name"; // WHERE tid IN (" . db_placeholders($url_tids) . ")
	$result = db_query ( $sql ); // $result = db_query($sql, $url_tids);
	$field_event_type_tid = isset($_GET['field_event_type_tid'])? $_GET['field_event_type_tid']:'';
	$sql_hs = 'SELECT th.parent
            FROM taxonomy_term_data td
            INNER JOIN taxonomy_vocabulary v ON v.vid = td.vid
            inner join taxonomy_term_hierarchy th on td.tid=th.tid
            WHERE v.vid = 8 and td.tid=:tid';
	$parent = db_query($sql_hs, array(':tid' => $field_event_type_tid))->fetchCol();
	if ($parent) {
		$parent = reset($parent);
	}
	
	$styles = array();
	if (!$field_event_type_tid) {
		$styles ['class'] [] = 'hover';
	}
	$content .= '<li>' . l ( '全部', 'touzi-event',  array (
			'attributes' => $styles
	) ) . '</li>';
	foreach ( $result as $term ) {
		$query = array('query' => array('field_event_type_tid' => $term->tid));
			
		//$href = url('touzi-event', $query);
		$styles = array();
		if ($parent && $parent == $term->tid || $field_event_type_tid && $field_event_type_tid == $term->tid) {
			$styles ['class'] [] = 'hover';
		}
		
		$content .= '<li>' . l ( $term->name, 'touzi-event', $query + array (
				'attributes' => $styles 
		) ) . '</li>';
	}
	
	$content .= '</ul></div><div class="children_terms"><ul class="list-unstyled left-nav">';
	
	if ($field_event_type_tid) {
		$sql = "SELECT td.tid, td.name
	            FROM taxonomy_term_data td
	            INNER JOIN taxonomy_vocabulary v ON v.vid = td.vid
	            inner join taxonomy_term_hierarchy th on td.tid=th.tid and th.parent=:parent
	            WHERE v.vid = 8
	            ORDER BY td.weight, td.name"; // WHERE tid IN (" . db_placeholders($url_tids) . ")
		$result = db_query ( $sql, array(':parent' => $parent? $parent:$field_event_type_tid) ); // $result = db_query($sql, $url_tids);
		foreach ( $result as $term ) {
					
			$query = array('query' => array('field_event_type_tid' => $term->tid));
				
			//$href = url('touzi-event', $query);
			$styles = array();
			if ($field_event_type_tid && $field_event_type_tid == $term->tid) {
				$styles ['class'] [] = 'hover';
			}
		
			$content .= '<li>' . l ( $term->name, 'touzi-event', $query + array (
					'attributes' => $styles
			) ) . '</li>';
		}
	}
	$content .= '</ul></div>';
	
	return $content;
}