<?php
require_once dirname ( __FILE__ ) . '/manage_account.api.inc';

define('ROLE_PARTNER', 5);
define('ROLE_INVESTOR', 6);
/**
 * Implement hook_form_alter().
 */
function manage_account_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'user_login') {
		//$form ['name'] ['#title_display'] = 'invisible';
		//$form ['pass'] ['#title_display'] = 'invisible';
		drupal_set_title(t('登录'));
		unset($form['name']['#description']);
		unset($form['pass']['#description']);
	}
	if ($form_id == 'user_register_form' || $form_id == 'user_profile_form') {
		$form['account']['pass']['#type'] = 'password';
		$form['account']['pass']['#title'] = t('Password');
		unset($form['account']['mail']['#description']);
	  unset($form['account']['pass']['#description']);
		if ($form_id == 'user_register_form') {
			unset($form['account']['name']['#description']);
			// 把电话作为注册用的唯一名字
			$form['account']['name']['#title'] = t('电话');
			$form['account']['name']['#title_display'] = 'invisible';
			$form['account']['name']['#attributes']['placeholder'] = t('请输入11位手机号码');
			$form['account']['name']['#attributes']['class'][] = 'friendly-register-name';
			hide($form['account']['mail']);
			//unset($form['account']['mail']['#required']);
			$form['account']['pass']['#title_display'] = 'invisible';
			$form['account']['pass']['#attributes']['placeholder'] = t('请输入密码');
			$form['field_real_name'][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
			$form['field_real_name'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = t('请输入用户名');
			$form['actions']['submit']['#attributes']['class'] = array('btn-primary', 'btn-block', 'loginBtn');
			//投资人选项 创业者
			$form['role'] = array(
					'#type' => 'radios',
					'#title' => '投资人还是创业者',
					'#required' => TRUE,
					'#options' => array(ROLE_INVESTOR => t('投资人'), ROLE_PARTNER => t('创业者')),
					'#default_value' => NULL,
					'#title_display' => 'invisible'
			);
			$form['agreement'] = array(
					'#type' => 'checkbox',
					'#title' => '我已阅读并同意<span><a href="/">《萌牙创投服务协议》</a></span>',
					'#required' => TRUE,
		  );
			$form['#validate'][] = 'manage_account_register_validate';
			//array_unshift
			$form['#submit'][] = 'manage_account_register_submit';
			//hide($form['field_address']);
			drupal_set_title(t('注册'));
		}
		if ($form_id == 'user_profile_form') {
			//hide($form['account']['mail']);
			hide($form['account']['pass']);
			hide($form['account']['current_pass']);
			hide($form['account']['current_pass_required_values']);
			//hide($form['account']['mail']);
			hide($form['locale']);
			hide($form['flag_friend']);
			hide($form['field_sourceid']);
			hide($form['field_origin']);
			
			//$form['account']['pass']['#title_display'] = 'invisible';
		}
	}
	if ($form['#id'] == 'views-exposed-form-investors-page') {
		unset($form['investregion']['#options']['不限']);
		foreach(element_children($form) as $key) {			
			if ($form[$key]['#type'] == 'select') {
				$form[$key]['#options']['All'] = '全部';
			}
		}
		
	}
}

function manage_account_register_validate(&$form, &$form_state) {
	$role = $form_state['values']['role'];
	$form_state['values']['roles'][$role] = 1;
	$form_state['values']['field_phone_number'][LANGUAGE_NONE][0]['value'] = $form_state['values']['name'];
	//dpm($form_state, 's');
}

function manage_account_register_submit(&$form, &$form_state) {
	global $user;
	$role = $form_state['values']['role'];
	if ($role == ROLE_INVESTOR) {
		$path = 'user/' . $user->uid . '/edit/preference_setting';
		drupal_goto($path);
	}
	if ($role == ROLE_PARTNER) {
		$path = 'user/' . $user->uid . '/edit/financing_demand';
		drupal_goto($path);
	}
}
